In [1]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)
print(A.shape)

# 転置
print(A.T)
print(A.T.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3)


In [2]:
B = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(B)
print(B.shape)

# 転置
print(B.T)
print(B.T.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
(5, 2)


In [3]:
# バッチサイズを指定
N = 20

# 前の層のニューロン数を指定
D = 50

# 次の層のニューロン数を指定
H = 10

# (仮の)入力を作成
X = np.random.rand(N, D)
print(X.shape)

# (仮の)重みを作成
W = np.random.rand(D, H)
print(W.shape)

# (仮の)バイアスを作成
b = np.random.rand(H)
print(b.shape)

(20, 50)
(50, 10)
(10,)


In [4]:
# 重み付き和を計算
Y = np.dot(X, W) + b
print(Y.shape)

(20, 10)


In [5]:
# (仮の)逆伝播の入力を作成
dY = np.random.rand(N, H)
print(dY.shape)

(20, 10)


In [6]:
# 順伝播の入力の勾配を計算
dX = np.dot(dY, W.T)
print(dX.shape)

# 重みの勾配を計算
dW = np.dot(X.T, dY)
print(dW.shape)

# バイアスの勾配を計算
db = np.sum(dY, axis=0)
print(db.shape)

(20, 50)
(50, 10)
(10,)


In [7]:
# Affineレイヤの実装
class Affine:
    # 初期化メソッド
    def __init__(self, W, b):
        # パラメータを保存
        self.W = W # 重み
        self.b = b # バイアス
        
        # 入力と勾配を初期化
        self.x = None # 順伝播の入力
        self.dW = None # 重みの勾配
        self.db = None # バイアスの勾配
    
    # 順伝播メソッド
    def forward(self, x):
        # 順伝播の入力を保存
        self.x = x
        
        # 重み付き和を計算
        out = np.dot(x, self.W) + self.b
        return out
    
    # 逆伝播メソッド
    def backward(self, dout):
        # 勾配を計算
        
        dx = np.dot(dout, self.W.T)      # 順伝播の入力の勾配
        self.dW = np.dot(self.x.T, dout) # 重みの勾配
        self.db = np.sum(dout, axis=0)   # バイアスの勾配
        
        # 順伝播の入力の勾配を出力
        return dx


In [8]:
# Affineレイヤのインスタンスを作成
layer = Affine(W, b)
print(layer.x)
print(layer.W.shape)
print(layer.b.shape)

None
(50, 10)
(10,)


In [9]:
# 順伝播を計算
Y = layer.forward(X)
print(Y.shape)

(20, 10)


In [10]:
# 逆伝播を計算
dX = layer.backward(dY)
print(dX.shape)
print(layer.dW.shape)
print(layer.db.shape)

(20, 50)
(50, 10)
(10,)
