In [5]:
import numpy as np

# 複数データに対応した交差エントロピー誤差
# 仮のニューラルネットワークの出力
y = np.array([
    [0.1,0.05,0.6,0.0,0.05,0.1,0.0,0.1,0.0,0.0],
    [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
    [0.1,0.05,0.1,0.0,0.05,0.1,0.0,0.6,0.0,0.0]
])
print(y)
print(y.shape)

# 仮の教師データを作成 (損失関数の計算は学習過程にあるので、テストデータではないのが明か)
t = np.array([
    [0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,0],
    [0,0,1,0,0,0,0,0,0,0]
])
print(t)
print(t.shape)

[[0.1  0.05 0.6  0.   0.05 0.1  0.   0.1  0.   0.  ]
 [0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1 ]
 [0.1  0.05 0.1  0.   0.05 0.1  0.   0.6  0.   0.  ]]
(3, 10)
[[0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0]]
(3, 10)


In [6]:
# 微小な値を設定
delta = 1e-7

# 出力の対数をとる
log_y = np.log(y + delta)
print(np.round(log_y, 2))

[[ -2.3   -3.    -0.51 -16.12  -3.    -2.3  -16.12  -2.3  -16.12 -16.12]
 [ -2.3   -2.3   -2.3   -2.3   -2.3   -2.3   -2.3   -2.3   -2.3   -2.3 ]
 [ -2.3   -3.    -2.3  -16.12  -3.    -2.3  -16.12  -0.51 -16.12 -16.12]]


In [7]:
# 教師データと出力の対数の積を計算
tmp = t * log_y
print(np.round(tmp, 2))
# 教師データと出力の対数の積の和を計算
tmp = np.sum(t * np.log(y + delta))
print(tmp)

[[-0.   -0.   -0.51 -0.   -0.   -0.   -0.   -0.   -0.   -0.  ]
 [-0.   -0.   -0.   -0.   -0.   -0.   -0.   -0.   -2.3  -0.  ]
 [-0.   -0.   -2.3  -0.   -0.   -0.   -0.   -0.   -0.   -0.  ]]
-5.11599364308843


In [8]:
# 複数データなので、バッチサイズで割る
batch_size = y.shape[0]
print(batch_size)

# 交差エントロピー誤差を計算
E = -np.sum(t * np.log(y + delta)) / batch_size
print(E)

3
1.70533121436281
