In [1]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3) # ガウス分布で初期化
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [2]:
net = simpleNet()
print(net.W) # 重みパラメータ

[[ 0.94677196  1.28646126  0.47905993]
 [-1.1319502  -0.19138289  0.92510387]]


In [3]:
x = np.array([0.6,0.9])
p = net.predict(x)
print(p)
np.argmax(p)

[-0.45069201  0.59963215  1.12002944]


2

In [4]:
t = np.array([0,0,1])
net.loss(x, t)

0.5889966096571844

In [5]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.06921456  0.19785519 -0.26706975]
 [ 0.10382184  0.29678278 -0.40060462]]
